# Generated by Django 5.1.7 on 2025-03-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('keywords', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.JSONField()),
            ],
            options={
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('history', models.ManyToManyField(blank=True, related_name='readers', to='recommender.book')),
                ('recommendations', models.ManyToManyField(blank=True, related_name='possible_readers', to='recommender.book')),
            ],
        ),
    ]
